services:
  bot:
    build:
      dockerfile: Dockerfile
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
secrets:
  neo4j_auth_file:
    file: secrets/neo4j_auth.txt


